### ISSUE TITLE
The Mod always aborts itself

### ISSUE THREAD

**Issue by ghost** [LotsofEds/DiversePD-IVSDK#2]
[LotsofEds](https://github.com/LotsofEds) This is a weird issue with the mod, because whenever I play the game (either GTA IV, EFLC or VCNE) the mod works fine at first but then some of its features stop working for unknown reason.

After checking the IVSDKDotNet console, it turns out that the script just aborted itself, even I checked out in the manager and it is not included in the list of loaded scripts.

I hope you fix this issue and I wish you the best.

**Comment by LotsofEds** [comment]
Should be fixed now, thanks.

**Comment by GTATrilogyGames** [comment]
[LotsofEds](https://github.com/LotsofEds) Hey man but still doesn't work. did you forget to include .dll file?

**Comment by LotsofEds** [comment]
Yeah my bad, uploaded the wrong file, should be good now for realsies.

**Comment by GTATrilogyGames** [comment]
[LotsofEds](https://github.com/LotsofEds) Hey man! I guess the mod still aborts itself no matter what, can you fix it?

**Comment by LotsofEds** [comment]
Looking into it.

EDIT: Fixed. Sorry for that.

**Comment by GTATrilogyGames** [comment]
[LotsofEds](https://github.com/LotsofEds) no problem, BTW, sorry for bothering but when I got 5/6 stars in VCNE the mod aborts itself, I hope you find this issue :(

**Comment by LotsofEds** [comment]
You have a discord account? PM me there, username is ServalEd

**Comment by GTATrilogyGames** [comment]
[LotsofEds](https://github.com/LotsofEds) Did you mean message me there or my Discord server?
edit: nevermind I understand
Yeah I have one the username is GTATrilogyGames
